---
title: "Conversatorios Cohesión Social 2025"
author: "Observatorio de Cohesión Social"
format: html
editor: visual
lang: es
bibliography: "input/ocs.bib"
---

# Propósito

En su primera etapa, el trabajo del Observatorio de Cohesión Social se centró en desarrollar un marco teórico que permitiera operacionalizar el concepto de cohesión social [@castillo_hacia_2021; @castillo_conceptos_2021]. A partir de este trabajo, se generaron informes describiendo la situación social en Chile [@castillo_cohesion_2022; @barozet_clases_2021]. Además, se tomó como base para la construcción de una [plataforma interactiva](https://ocs-coes.netlify.app/app/) que permite visualizar indicadores de cohesión social con datos internacionales, transversales y longitudinales.

Esta propuesta se enmarca en una segunda etapa que busca expander el trabajo realizado anteriormente. Por un lado, se actualizará el sitio web del Observatorio. Con ello, se presentará una nueva versión de su visualizador, que incorporará nuevas fuentes de datos a nivel internacional y nacional, dotando a la comunidad de una herramienta que proveerá datos de calidad sobre la situación de la cohesión social en Chile y en el mundo.

Por otro lado, en un contexto de deterior de la convivencia cívica y de alta desconfianza hacia las insituciones y autoridades [@araujo_primer_2022], resulta clave generar un espacio de discusión sobre los desafíos de la cohesión social en Chile y América Latina.

De tal modo, este **Ciclo de Conversatorios sobre Cohesión Social** pretenden dotar ese espacio, triangulando el trabajo previo del Observatorio y la amplia producción académica de investigadores COES sobre el tema. De tal modo, se busca promover la discusión sobre los desafíos políticos, teóricos y metodológicos de la cohesión social en Chile y América Latina. Dirigido a estudiantes de pre y postgrado, académicos y la comunidad universitaria en general, los Conversatorios sobre Cohesión Social buscan fomentar la reflexión crítica, difundir y potenciar la investigación sobre cohesión social

Siguiendo el trabajo previo del Observatorio, se abodará la cohesión social desde tres dimensiones clave: 1) **Desafíos regionales y nacionales** para la cohesión social, incluyendo la discusión política, teórica y metodológica; 2) **La dimensión horizontal** de la cohesión social, incluyendo discusiones sobre el sentido de pertenencia, la vida barrial y las redes sociales; 3) **La dimensión vertical** de la cohesión social, esto es, la participación política, la confianza en las instituciones y las percepciones de justicia.

Cada uno de estos ejes protagonizará un conversatorio, como se describe a continuación:

# Conversatorios

## Primer Conversatorio: Cohesión Social y la Convivencia Cotidiana

Esta instancia se plantea como una instancia para reflexionar sobre la dimensión horizontal de la cohesión social. Como tal, en este conversatorio se debatirán problemáticas de convivencia cotidiana entre invididuos y grupos sociales, sus sentidos de pertenencia, sus identidades nacionales y barriales, su confianza interpersonal y su comportamiento prosocial [@castillo_hacia_2021]

**Fecha Tentativa**: 15 de junio

## Segundo Conversatorio: Desafíos de la Cohesión Social en Chile y América Latina.

Este conversatorio se plantea como una instancia de reflexión acerca de los desafíos de la Cohesión Social en Chile y América Latina, tanto a nivel político -- como una dimensión de la vida social que tensiona la convivencia en nuestras sociedad -- como en un constitución como objetivo sociológico.

De tal modo, donde las problemáticas relacionadas a la convivencia, la desigualdad y la legitimidad del orden democrático persisten en gran parte de América Latina [@undp_trapped_2023], nos preguntamos que ¿qué efectos tiene el deterioro de la cohesión social en los países de la región? ¿cómo pueden las ciencias sociales estudiar este fenómeno? ¿cuál es su potencial para dar soluciones a estas problemáticas?

Este conversatorio no contaría solo con la participación de académicos, sino que también se invitaría a actores políticos que puedan dar su visión de los desafíos de la cohesión social en Chile desde la persperctiva de sus territorios. Claudio Castro, alcade de Renca y miembros del Consejo Asesor Social ha demostrado interés en participar en una instancia de estas características. A él, se le podría sumar un segundo alcalde o alcaldesa.

**Fecha Tentativa**: 22 de agosto

## Tercer Conversatorio: La Cohesión Social en el contexto de las elecciones presidenciales: Instituciones, autoridad y política.

Por último, el tercer conversatorio estará enfocado en la dimensión vertical de la cohesión social, es decir, en la relación de los ciudadanos con el Estado, la participación política, la confianza en las instituciones y sus autoridades [@castillo_hacia_2021], todo esto en el contexto de las venideras elecciones presidenciales.

**Fecha Tentativa**: Durante la Conferencia COES, Octubre 2025

# Propuesta de Invitados

+------------------------------------------------------------------------------------------------------+----------------------+----------------------------------------------------------------------+--------------------------------------+
| Conversatorio                                                                                        | Moderación           | Invitados                                                            | Alternativas                         |
+======================================================================================================+======================+======================================================================+======================================+
| Cohesión Social y Convivencia Cotidiana                                                              | Nicolás Angelcos     | Quentin Ramond (U. Mayor; COES)                                      | 1.  Alejandra Rasse                  |
|                                                                                                      |                      |                                                                      | 2.  Felipe Link                      |
|                                                                                                      |                      | Macarena Bonhomme (UMayor, COES)                                     | 3.  Macarena Bonhomme                |
|                                                                                                      |                      |                                                                      | 4.  Vicente Espinoza                 |
|                                                                                                      |                      |                                                                      | 5.  Macarena Orchard                 |
|                                                                                                      |                      |                                                                      | 6.  Raimundo Frei                    |
|                                                                                                      |                      |                                                                      | 7.  Valentina Abufhele               |
|                                                                                                      |                      |                                                                      | 8.  Jorge Atria                      |
+------------------------------------------------------------------------------------------------------+----------------------+----------------------------------------------------------------------+--------------------------------------+
| Desafíos de la Cohesión Social en Chile y América Latina                                             | Juan Carlos Castillo | Matías Bargsted (PUC, COES)                                          | 1.  Daniel Miranda                   |
|                                                                                                      |                      |                                                                      | 2.  Jorge Atria                      |
|                                                                                                      |                      | Macarena Orchard (UDP, COES)                                         | 3.  Rodolfo Disi                     |
|                                                                                                      |                      |                                                                      | 4.  Maya Zilveti                     |
|                                                                                                      |                      | Claudio Castro (Municipalidad de Renca) y un segundo alcade/alcadesa | 5.  Matías Cosiño                    |
|                                                                                                      |                      |                                                                      | 6.  Emmanuelle Barozet               |
|                                                                                                      |                      |                                                                      | 7.  Nicolás Somma                    |
|                                                                                                      |                      |                                                                      | 8.  Roberto González                 |
|                                                                                                      |                      |                                                                      | 9.  Annie Duffey                     |
|                                                                                                      |                      |                                                                      | 10. Raimundo Frei                    |
|                                                                                                      |                      |                                                                      |                                      |
|                                                                                                      |                      |                                                                      | **Propuestas de Alcade/Alcadesa**    |
|                                                                                                      |                      |                                                                      |                                      |
|                                                                                                      |                      |                                                                      | 1.  Catalina San Martín (Las Condes) |
|                                                                                                      |                      |                                                                      | 2.  Camila Merino (Vitacura)         |
|                                                                                                      |                      |                                                                      | 3.  Agustín Iglesias (Independencia) |
|                                                                                                      |                      |                                                                      | 4.  Carlos Palacios (La Reina)       |
+------------------------------------------------------------------------------------------------------+----------------------+----------------------------------------------------------------------+--------------------------------------+
| Cohesion Social en el contexto de las elecciones presidenciales: Instituciones, autoridad y política | Emmanuelle Barozet   | Kathya Araujo (USACH)                                                | 1.  Daniel Mansuy                    |
|                                                                                                      |                      |                                                                      | 2.  M.A. Garretón                    |
|                                                                                                      | \                    | Cristóbal Belloio (UAI)                                              | 3.  Juan Pablo Luna                  |
|                                                                                                      |                      |                                                                      | 4.  María Luisa Méndez               |
|                                                                                                      |                      |                                                                      | 5.  Alfredo Joigant                  |
|                                                                                                      |                      |                                                                      | 6.  Mónica Gerber                    |
|                                                                                                      |                      |                                                                      | 7.  Matías Bargsted                  |
+------------------------------------------------------------------------------------------------------+----------------------+----------------------------------------------------------------------+--------------------------------------+

## Dinámica de la Actividad

-   Primer segmento: El moderador introduce el tema de la discusión a partir de su propia experiencia como investigador. Por lo demás, el Observatorio proveerá insumos a la discusión a partir de su propio trabajo, particularmente desde los hallazgos disponibles en los visualizadores del OCS.

-   Segundo segmento: Dos investigadores/as comentan el primer segmento a la luz de sus propias investigaciones.

## 
